@endpoint=https://cmd-zeta.vercel.app/api

### "ping"
POST {{endpoint}}
Content-Type: application/json
Accept: application/json

{
  "type": 1
}

###
POST {{endpoint}}
Content-Type: application/json
Accept: application/json

{
  "type": 1
}

